trigger:
  batch: true
  branches:
    include:
      - '*'

variables:
  solution: '**\*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  artifactName: 'SNOW-Monitoring'

stages:
- stage: BuildMP

  jobs:
    - job: BuildJob
      displayName: Build Management Pack
      pool:
        name: Build Agents
        demands:
        - msbuild
        - visualstudio

        steps:
        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
            clean: true


